# Generated by Django 4.1.2 on 2022-10-31 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
